import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import { CatalogService } from './catalog.service';

export interface SitemapUrl {
  loc: string;
  lastmod: string;
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority: number;
}

export interface SitemapConfig {
  baseUrl: string;
  storeId: string;
  maxUrls?: number;
}

@Injectable({
  providedIn: 'root'
})
export class SitemapService {
  private http = inject(HttpClient);
  private catalogService = inject(CatalogService);

  /**
   * Gera sitemap XML completo
   */
  generateSitemap(config: SitemapConfig): Observable<string> {
    return this.getSitemapUrls(config).pipe(
      map(urls => this.buildSitemapXml(urls)),
      catchError(error => {
        console.error('[SitemapService] Error generating sitemap:', error);
        return of(this.getMinimalSitemap(config.baseUrl));
      })
    );
  }

  /**
   * Gera robots.txt
   */
  generateRobotsTxt(config: SitemapConfig): string {
    return `User-agent: *
Allow: /

# Sitemaps
Sitemap: ${config.baseUrl}/sitemap.xml

# Crawl delay
Crawl-delay: 1

# Disallow admin paths
Disallow: /admin/
Disallow: /api/
Disallow: /private/

# Allow important paths
Allow: /c/
Allow: /p/
Allow: /assets/

# Block development files
Disallow: /*.json$
Disallow: /*.map$
Disallow: /*.ts$

# Generated by Storefront SEO Service
# Last updated: ${new Date().toISOString()}`;
  }

  /**
   * Coleta todas as URLs para o sitemap
   */
  private getSitemapUrls(config: SitemapConfig): Observable<SitemapUrl[]> {
    const urls: SitemapUrl[] = [];
    const now = new Date().toISOString();
    
    // URL da home
    urls.push({
      loc: config.baseUrl,
      lastmod: now,
      changefreq: 'daily',
      priority: 1.0
    });

    // URLs de categorias (mock)
    const categories = this.getMockCategories();
    categories.forEach(category => {
      urls.push({
        loc: `${config.baseUrl}/c/${category.slug}`,
        lastmod: category.updatedAt || now,
        changefreq: 'weekly',
        priority: 0.8
      });
    });

    // URLs de produtos (mock)
    const products = this.getMockProducts();
    products.forEach(product => {
      urls.push({
        loc: `${config.baseUrl}/p/${product.slug}`,
        lastmod: product.updatedAt || now,
        changefreq: 'monthly',
        priority: 0.6
      });
    });

    // Limita URLs se necessário
    const maxUrls = config.maxUrls || 50000;
    return of(urls.slice(0, maxUrls));
  }

  /**
   * Constrói XML do sitemap
   */
  private buildSitemapXml(urls: SitemapUrl[]): string {
    const urlElements = urls.map(url => `  <url>
    <loc>${this.escapeXml(url.loc)}</loc>
    <lastmod>${url.lastmod}</lastmod>
    <changefreq>${url.changefreq}</changefreq>
    <priority>${url.priority.toFixed(1)}</priority>
  </url>`).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlElements}
</urlset>`;
  }

  /**
   * Sitemap mínimo em caso de erro
   */
  private getMinimalSitemap(baseUrl: string): string {
    const now = new Date().toISOString();
    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${baseUrl}</loc>
    <lastmod>${now}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>`;
  }

  /**
   * Escapa caracteres especiais para XML
   */
  private escapeXml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }

  /**
   * Mock de categorias (em produção viria da API)
   */
  private getMockCategories() {
    return [
      { slug: 'electronics', updatedAt: '2024-01-15T10:30:00Z' },
      { slug: 'clothing', updatedAt: '2024-01-14T15:20:00Z' },
      { slug: 'books', updatedAt: '2024-01-13T09:45:00Z' },
      { slug: 'home-garden', updatedAt: '2024-01-12T14:10:00Z' },
      { slug: 'sports', updatedAt: '2024-01-11T16:30:00Z' }
    ];
  }

  /**
   * Mock de produtos (em produção viria da API)
   */
  private getMockProducts(): Array<{slug: string, updatedAt: string}> {
    const products: Array<{slug: string, updatedAt: string}> = [];
    const categories = ['electronics', 'clothing', 'books', 'home-garden', 'sports'];
    
    categories.forEach(category => {
      for (let i = 1; i <= 10; i++) {
        products.push({
          slug: `${category}-product-${i}`,
          updatedAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString()
        });
      }
    });

    return products;
  }
}