import { APP_BASE_HREF } from '@angular/common';
import { CommonEngine, isMainModule } from '@angular/ssr/node';
import express from 'express';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import bootstrap from './main.server';
import { SitemapService } from './app/services/sitemap.service';

const serverDistFolder = dirname(fileURLToPath(import.meta.url));
const browserDistFolder = resolve(serverDistFolder, '../browser');
const indexHtml = join(serverDistFolder, 'index.server.html');

const app = express();
const commonEngine = new CommonEngine();

/**
 * SEO Routes - Sitemap and Robots.txt
 */
app.get('/sitemap.xml', async (req, res) => {
  try {
    const baseUrl = getBaseUrl(req);
    const storeId = getStoreId(req);
    
    // Mock sitemap generation (em produção, usaria SitemapService injetado)
    const sitemap = generateSitemap(baseUrl, storeId);
    
    res.set({
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600', // Cache por 1 hora
    });
    
    res.send(sitemap);
  } catch (error) {
    console.error('Error generating sitemap:', error);
    res.status(500).send('Error generating sitemap');
  }
});

app.get('/robots.txt', (req, res) => {
  try {
    const baseUrl = getBaseUrl(req);
    const robotsTxt = generateRobotsTxt(baseUrl);
    
    res.set({
      'Content-Type': 'text/plain',
      'Cache-Control': 'public, max-age=86400', // Cache por 24 horas
    });
    
    res.send(robotsTxt);
  } catch (error) {
    console.error('Error generating robots.txt:', error);
    res.status(500).send('Error generating robots.txt');
  }
});

/**
 * Helper functions for SEO routes
 */
function getBaseUrl(req: express.Request): string {
  const protocol = req.headers['x-forwarded-proto'] || req.protocol || 'https';
  const host = req.headers['x-forwarded-host'] || req.headers.host || req.get('host');
  return `${protocol}://${host}`;
}

function getStoreId(req: express.Request): string {
  const host = req.headers.host || '';
  const path = req.path || '';
  
  if (host.includes('pink') || path.includes('/pink')) {
    return 'pink';
  }
  
  if (host.includes('minimal') || path.includes('/minimal')) {
    return 'minimal';
  }
  
  return 'default';
}

function generateSitemap(baseUrl: string, storeId: string): string {
  const now = new Date().toISOString();
  
  // URLs estáticas
  const urls = [
    { loc: baseUrl, lastmod: now, changefreq: 'daily', priority: '1.0' },
    // Categorias mock
    { loc: `${baseUrl}/c/electronics`, lastmod: '2024-01-15T10:30:00Z', changefreq: 'weekly', priority: '0.8' },
    { loc: `${baseUrl}/c/clothing`, lastmod: '2024-01-14T15:20:00Z', changefreq: 'weekly', priority: '0.8' },
    { loc: `${baseUrl}/c/books`, lastmod: '2024-01-13T09:45:00Z', changefreq: 'weekly', priority: '0.8' },
    { loc: `${baseUrl}/c/home-garden`, lastmod: '2024-01-12T14:10:00Z', changefreq: 'weekly', priority: '0.8' },
    // Produtos mock
    { loc: `${baseUrl}/p/laptop-gaming`, lastmod: '2024-01-10T12:00:00Z', changefreq: 'monthly', priority: '0.6' },
    { loc: `${baseUrl}/p/smartphone-pro`, lastmod: '2024-01-09T14:30:00Z', changefreq: 'monthly', priority: '0.6' },
    { loc: `${baseUrl}/p/t-shirt-cotton`, lastmod: '2024-01-08T16:15:00Z', changefreq: 'monthly', priority: '0.6' },
    { loc: `${baseUrl}/p/coffee-maker`, lastmod: '2024-01-07T10:45:00Z', changefreq: 'monthly', priority: '0.6' },
  ];
  
  const urlElements = urls.map(url => `  <url>
    <loc>${escapeXml(url.loc)}</loc>
    <lastmod>${url.lastmod}</lastmod>
    <changefreq>${url.changefreq}</changefreq>
    <priority>${url.priority}</priority>
  </url>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlElements}
</urlset>`;
}

function generateRobotsTxt(baseUrl: string): string {
  return `User-agent: *
Allow: /

# Sitemaps
Sitemap: ${baseUrl}/sitemap.xml

# Crawl delay
Crawl-delay: 1

# Disallow admin paths
Disallow: /admin/
Disallow: /api/
Disallow: /private/

# Allow important paths
Allow: /c/
Allow: /p/
Allow: /assets/

# Block development files
Disallow: /*.json$
Disallow: /*.map$
Disallow: /*.ts$

# Generated by Storefront SEO Service
# Last updated: ${new Date().toISOString()}`;
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Serve static files from /browser
 */
app.get(
  '**',
  express.static(browserDistFolder, {
    maxAge: '1y',
    index: 'index.html'
  }),
);

/**
 * Handle all other requests by rendering the Angular application.
 */
app.get('**', (req, res, next) => {
  const { protocol, originalUrl, baseUrl, headers } = req;

  commonEngine
    .render({
      bootstrap,
      documentFilePath: indexHtml,
      url: `${protocol}://${headers.host}${originalUrl}`,
      publicPath: browserDistFolder,
      providers: [{ provide: APP_BASE_HREF, useValue: baseUrl }],
    })
    .then((html) => res.send(html))
    .catch((err) => next(err));
});

/**
 * Start the server if this module is the main entry point.
 * The server listens on the port defined by the `PORT` environment variable, or defaults to 4000.
 */
if (isMainModule(import.meta.url)) {
  const port = process.env['PORT'] || 4001;
  app.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

export default app;
